name: First pipeline

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: posts-test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping"

    steps: # 步驟
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.ci .env
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: phpstan
        run: ./vendor/bin/phpstan analyse --memory-limit=1G
      - name: phpinsights
        run: |
          php artisan insights --no-interaction \
          --min-quality=90 --min-complexity=90 \
          --min-architecture=90 --min-style=90 \
          --ansi --format=github-action
      - name: Run tests
        run: php artisan test
